/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class TMientras extends Token
{
    public TMientras()
    {
        super.setText("mientras");
    }

    public TMientras(int line, int pos)
    {
        super.setText("mientras");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMientras(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMientras(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMientras text.");
    }
}
