/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class TRetornar extends Token
{
    public TRetornar()
    {
        super.setText("retornar");
    }

    public TRetornar(int line, int pos)
    {
        super.setText("retornar");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRetornar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRetornar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRetornar text.");
    }
}
