/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class TSino extends Token
{
    public TSino()
    {
        super.setText("sino");
    }

    public TSino(int line, int pos)
    {
        super.setText("sino");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSino(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSino(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSino text.");
    }
}
