/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class TVerdadero extends Token
{
    public TVerdadero()
    {
        super.setText("verdadero");
    }

    public TVerdadero(int line, int pos)
    {
        super.setText("verdadero");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVerdadero(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVerdadero(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVerdadero text.");
    }
}
