/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.parser;

import lexing.node.*;
import lexing.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 0;
    }

    @Override
    public void caseTIdent(@SuppressWarnings("unused") TIdent node)
    {
        this.index = 1;
    }

    @Override
    public void caseTArithOp(@SuppressWarnings("unused") TArithOp node)
    {
        this.index = 2;
    }

    @Override
    public void caseTRelOp(@SuppressWarnings("unused") TRelOp node)
    {
        this.index = 3;
    }

    @Override
    public void caseTParen(@SuppressWarnings("unused") TParen node)
    {
        this.index = 4;
    }

    @Override
    public void caseTUnknown(@SuppressWarnings("unused") TUnknown node)
    {
        this.index = 5;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 6;
    }
}
