/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

public final class TDo extends Token
{
    public TDo()
    {
        super.setText("hacer");
    }

    public TDo(int line, int pos)
    {
        super.setText("hacer");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDo(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDo(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDo text.");
    }
}
