/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

public final class TInt extends Token
{
    public TInt()
    {
        super.setText("entero");
    }

    public TInt(int line, int pos)
    {
        super.setText("entero");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TInt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInt(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TInt text.");
    }
}
