/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

public final class TVoid extends Token
{
    public TVoid()
    {
        super.setText("vacio");
    }

    public TVoid(int line, int pos)
    {
        super.setText("vacio");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TVoid(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVoid(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TVoid text.");
    }
}
