/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

public final class TWhile extends Token
{
    public TWhile()
    {
        super.setText("mientras");
    }

    public TWhile(int line, int pos)
    {
        super.setText("mientras");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TWhile(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWhile(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TWhile text.");
    }
}
