/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.analysis;

import lexing.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAStart(AStart node);

    void caseTSi(TSi node);
    void caseTSino(TSino node);
    void caseTMientras(TMientras node);
    void caseTPara(TPara node);
    void caseTRetornar(TRetornar node);
    void caseTVerdadero(TVerdadero node);
    void caseTFalso(TFalso node);
    void caseTNumber(TNumber node);
    void caseTIdent(TIdent node);
    void caseTArithOp(TArithOp node);
    void caseTRelOp(TRelOp node);
    void caseTParen(TParen node);
    void caseTLbrace(TLbrace node);
    void caseTRbrace(TRbrace node);
    void caseTSemicolon(TSemicolon node);
    void caseTAssign(TAssign node);
    void caseTBlank(TBlank node);
    void caseTUnknown(TUnknown node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
