/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.parser;

import lexing.node.*;
import lexing.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTSi(@SuppressWarnings("unused") TSi node)
    {
        this.index = 0;
    }

    @Override
    public void caseTSino(@SuppressWarnings("unused") TSino node)
    {
        this.index = 1;
    }

    @Override
    public void caseTMientras(@SuppressWarnings("unused") TMientras node)
    {
        this.index = 2;
    }

    @Override
    public void caseTPara(@SuppressWarnings("unused") TPara node)
    {
        this.index = 3;
    }

    @Override
    public void caseTRetornar(@SuppressWarnings("unused") TRetornar node)
    {
        this.index = 4;
    }

    @Override
    public void caseTVerdadero(@SuppressWarnings("unused") TVerdadero node)
    {
        this.index = 5;
    }

    @Override
    public void caseTFalso(@SuppressWarnings("unused") TFalso node)
    {
        this.index = 6;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 7;
    }

    @Override
    public void caseTIdent(@SuppressWarnings("unused") TIdent node)
    {
        this.index = 8;
    }

    @Override
    public void caseTArithOp(@SuppressWarnings("unused") TArithOp node)
    {
        this.index = 9;
    }

    @Override
    public void caseTRelOp(@SuppressWarnings("unused") TRelOp node)
    {
        this.index = 10;
    }

    @Override
    public void caseTParen(@SuppressWarnings("unused") TParen node)
    {
        this.index = 11;
    }

    @Override
    public void caseTLbrace(@SuppressWarnings("unused") TLbrace node)
    {
        this.index = 12;
    }

    @Override
    public void caseTRbrace(@SuppressWarnings("unused") TRbrace node)
    {
        this.index = 13;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 14;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 15;
    }

    @Override
    public void caseTUnknown(@SuppressWarnings("unused") TUnknown node)
    {
        this.index = 16;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 17;
    }
}
