/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import java.util.*;
import lexing.analysis.*;

@SuppressWarnings("nls")
public final class AStart extends PStart
{
    private final LinkedList<TUnknown> _unknown_ = new LinkedList<TUnknown>();

    public AStart()
    {
        // Constructor
    }

    public AStart(
        @SuppressWarnings("hiding") List<?> _unknown_)
    {
        // Constructor
        setUnknown(_unknown_);

    }

    @Override
    public Object clone()
    {
        return new AStart(
            cloneList(this._unknown_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStart(this);
    }

    public LinkedList<TUnknown> getUnknown()
    {
        return this._unknown_;
    }

    public void setUnknown(List<?> list)
    {
        for(TUnknown e : this._unknown_)
        {
            e.parent(null);
        }
        this._unknown_.clear();

        for(Object obj_e : list)
        {
            TUnknown e = (TUnknown) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._unknown_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unknown_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unknown_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TUnknown> i = this._unknown_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TUnknown) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
