/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

public final class TClas extends Token
{
    public TClas()
    {
        super.setText("class");
    }

    public TClas(int line, int pos)
    {
        super.setText("class");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TClas(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTClas(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TClas text.");
    }
}
