/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.lexer;

import java.io.*;
import java.util.*;
import decaf.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TComment1(text, line, pos); }
    Token new1(String text, int line, int pos) { return new TComment2(text, line, pos); }
    Token new2(String text, int line, int pos) { return new TSpace(text, line, pos); }
    Token new3(int line, int pos) { return new TClas(line, pos); }
    Token new4(int line, int pos) { return new TPublic(line, pos); }
    Token new5(int line, int pos) { return new TStatic(line, pos); }
    Token new6(int line, int pos) { return new TVoid(line, pos); }
    Token new7(int line, int pos) { return new TMain(line, pos); }
    Token new8(int line, int pos) { return new TString(line, pos); }
    Token new9(int line, int pos) { return new TInt(line, pos); }
    Token new10(int line, int pos) { return new TFloat(line, pos); }
    Token new11(int line, int pos) { return new TFor(line, pos); }
    Token new12(int line, int pos) { return new TWhile(line, pos); }
    Token new13(int line, int pos) { return new TDo(line, pos); }
    Token new14(int line, int pos) { return new TIf(line, pos); }
    Token new15(int line, int pos) { return new TElse(line, pos); }
    Token new16(int line, int pos) { return new TAssign(line, pos); }
    Token new17(String text, int line, int pos) { return new TCompare(text, line, pos); }
    Token new18(int line, int pos) { return new TPlus(line, pos); }
    Token new19(int line, int pos) { return new TMinus(line, pos); }
    Token new20(int line, int pos) { return new TMult(line, pos); }
    Token new21(int line, int pos) { return new TDiv(line, pos); }
    Token new22(int line, int pos) { return new TLPar(line, pos); }
    Token new23(int line, int pos) { return new TRPar(line, pos); }
    Token new24(int line, int pos) { return new TLBrace(line, pos); }
    Token new25(int line, int pos) { return new TRBrace(line, pos); }
    Token new26(int line, int pos) { return new TLBracket(line, pos); }
    Token new27(int line, int pos) { return new TRBracket(line, pos); }
    Token new28(int line, int pos) { return new TComma(line, pos); }
    Token new29(int line, int pos) { return new TSemi(line, pos); }
    Token new30(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    Token new31(String text, int line, int pos) { return new TNumber(text, line, pos); }
    Token new32(String text, int line, int pos) { return new TMisc(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 3}, {14, 31, 1}, {32, 32, 4}, {33, 33, 5}, {34, 39, 1}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 1}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {63, 64, 1}, {65, 66, 19}, {67, 67, 20}, {68, 90, 19}, {91, 91, 21}, {92, 92, 1}, {93, 93, 22}, {94, 96, 1}, {97, 98, 23}, {99, 99, 24}, {100, 100, 23}, {101, 101, 25}, {102, 102, 26}, {103, 103, 23}, {104, 104, 27}, {105, 108, 23}, {109, 109, 28}, {110, 111, 23}, {112, 112, 29}, {113, 114, 23}, {115, 115, 30}, {116, 117, 23}, {118, 118, 31}, {119, 122, 23}, {123, 123, 32}, {124, 124, 1}, {125, 125, 33}, {126, 65535, 1}, },
            {},
            {},
            {},
            {},
            {{61, 61, 34}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 35}, },
            {{42, 42, 36}, {47, 47, 37}, },
            {{46, 46, 38}, {48, 57, 39}, {69, 69, 40}, {101, 101, 40}, },
            {},
            {{61, 61, 41}, },
            {{61, 61, 42}, },
            {{61, 61, 43}, },
            {{48, 57, 44}, {65, 90, 45}, {95, 95, 46}, {97, 122, 47}, },
            {{48, 95, -21}, {97, 97, 48}, {98, 122, 47}, },
            {},
            {},
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 107, 47}, {108, 108, 49}, {109, 122, 47}, },
            {{48, 95, -21}, {97, 109, 47}, {110, 110, 50}, {111, 114, 47}, {115, 115, 51}, {116, 122, 47}, },
            {{48, 107, -26}, {108, 108, 52}, {109, 122, 47}, },
            {{48, 95, -21}, {97, 97, 53}, {98, 122, 47}, },
            {{48, 95, -21}, {97, 104, 47}, {105, 105, 54}, {106, 122, 47}, },
            {{48, 95, -21}, {97, 97, 55}, {98, 113, 47}, {114, 114, 56}, {115, 116, 47}, {117, 117, 57}, {118, 122, 47}, },
            {{48, 104, -30}, {105, 105, 58}, {106, 122, 47}, },
            {{48, 95, -21}, {97, 97, 59}, {98, 122, 47}, },
            {},
            {},
            {},
            {{48, 57, 35}, {69, 101, -16}, },
            {{0, 41, 60}, {42, 42, 61}, {43, 65535, 60}, },
            {{0, 9, 62}, {10, 10, 63}, {11, 12, 62}, {13, 13, 63}, {14, 65535, 62}, },
            {{48, 57, 64}, {69, 101, -16}, },
            {{46, 101, -16}, },
            {{43, 43, 65}, {45, 45, 65}, {48, 57, 66}, },
            {},
            {},
            {},
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 99, 47}, {100, 100, 67}, {101, 122, 47}, },
            {{48, 95, -21}, {97, 97, 68}, {98, 122, 47}, },
            {{48, 95, -21}, {97, 115, 47}, {116, 116, 69}, {117, 122, 47}, },
            {{48, 115, -52}, {116, 116, 70}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 110, 47}, {111, 111, 71}, {112, 122, 47}, },
            {{48, 95, -21}, {97, 98, 47}, {99, 99, 72}, {100, 122, 47}, },
            {{48, 95, -21}, {97, 100, 47}, {101, 101, 73}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 113, 47}, {114, 114, 74}, {115, 122, 47}, },
            {{48, 104, -30}, {105, 105, 75}, {106, 122, 47}, },
            {{48, 95, -21}, {97, 97, 47}, {98, 98, 76}, {99, 122, 47}, },
            {{48, 109, -27}, {110, 110, 77}, {111, 122, 47}, },
            {{48, 98, -55}, {99, 99, 78}, {100, 122, 47}, },
            {{0, 65535, -38}, },
            {{0, 41, 79}, {43, 46, 79}, {47, 47, 80}, {48, 65535, 79}, },
            {{0, 65535, -39}, },
            {},
            {{48, 101, -40}, },
            {{48, 57, 66}, },
            {{48, 57, 66}, },
            {{48, 100, -56}, {101, 101, 81}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 114, 47}, {115, 115, 82}, {116, 122, 47}, },
            {{48, 100, -56}, {101, 101, 83}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 97, 84}, {98, 122, 47}, },
            {{48, 115, -52}, {116, 116, 85}, {117, 122, 47}, },
            {{48, 100, -56}, {101, 101, 86}, {102, 122, 47}, },
            {{48, 109, -27}, {110, 110, 87}, {111, 122, 47}, },
            {{48, 95, -21}, {97, 97, 88}, {98, 122, 47}, },
            {{48, 109, -27}, {110, 110, 89}, {111, 122, 47}, },
            {{48, 107, -26}, {108, 108, 90}, {109, 122, 47}, },
            {{48, 110, -54}, {111, 111, 91}, {112, 122, 47}, },
            {{48, 104, -30}, {105, 105, 92}, {106, 122, 47}, },
            {{0, 41, 93}, {42, 42, 94}, {43, 65535, 93}, },
            {},
            {{48, 109, -27}, {110, 110, 95}, {111, 122, 47}, },
            {{48, 100, -56}, {101, 101, 96}, {102, 122, 47}, },
            {{48, 113, -57}, {114, 114, 97}, {115, 122, 47}, },
            {{48, 115, -52}, {116, 116, 98}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 97, 99}, {98, 122, 47}, },
            {{48, 113, -57}, {114, 114, 100}, {115, 122, 47}, },
            {{48, 115, -52}, {116, 116, 101}, {117, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 98, -55}, {99, 99, 102}, {100, 122, 47}, },
            {{48, 104, -30}, {105, 105, 103}, {106, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 110, -54}, {111, 111, 104}, {112, 122, 47}, },
            {{0, 65535, -81}, },
            {{0, 41, 79}, {42, 42, 94}, {43, 65535, -63}, },
            {{48, 95, -21}, {97, 97, 105}, {98, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 110, -54}, {111, 111, 106}, {112, 122, 47}, },
            {{48, 104, -30}, {105, 105, 107}, {106, 122, 47}, },
            {{48, 109, -27}, {110, 110, 108}, {111, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 113, -57}, {114, 114, 109}, {115, 122, 47}, },
            {{48, 104, -30}, {105, 105, 110}, {106, 122, 47}, },
            {{48, 98, -55}, {99, 99, 111}, {100, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 98, -55}, {99, 99, 112}, {100, 122, 47}, },
            {{48, 115, -52}, {116, 116, 113}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 97, 114}, {98, 122, 47}, },
            {{48, 95, -21}, {97, 111, 47}, {112, 112, 115}, {113, 122, 47}, },
            {{48, 110, -54}, {111, 111, 116}, {112, 122, 47}, },
            {{48, 110, -54}, {111, 111, 117}, {112, 122, 47}, },
            {{48, 100, -56}, {101, 101, 118}, {102, 122, 47}, },
            {{48, 114, -70}, {115, 115, 119}, {116, 122, 47}, },
            {{48, 95, -21}, {97, 97, 120}, {98, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 107, -26}, {108, 108, 121}, {109, 122, 47}, },
            {{48, 122, -21}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 32, 2, 2, 2, 32, 22, 23, 20, 18, 28, 19, 32, 21, 31, 29, 17, 16, 17, 30, 30, 26, 27, 30, 30, 30, 30, 30, 30, 30, 30, 30, 24, 25, 17, 31, -1, -1, 31, 31, -1, 17, 17, 17, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 14, 30, -1, -1, -1, 0, 31, -1, 31, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, -1, 1, 30, 30, 30, 30, 30, 30, 30, 11, 30, 30, 15, 30, -1, -1, 30, 3, 30, 30, 30, 13, 30, 30, 30, 6, 8, 9, 30, 30, 30, 30, 30, 30, 30, 30, 30, 4, 5, 10, 12, 30, 7, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
