/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

public final class TFloat extends Token
{
    public TFloat()
    {
        super.setText("perpuluhan");
    }

    public TFloat(int line, int pos)
    {
        super.setText("perpuluhan");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TFloat(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFloat(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TFloat text.");
    }
}
