/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.lexer;

import java.io.*;
import java.util.*;
import decaf.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TComment1(text, line, pos); }
    Token new1(String text, int line, int pos) { return new TComment2(text, line, pos); }
    Token new2(String text, int line, int pos) { return new TSpace(text, line, pos); }
    Token new3(int line, int pos) { return new TClas(line, pos); }
    Token new4(int line, int pos) { return new TPublic(line, pos); }
    Token new5(int line, int pos) { return new TStatic(line, pos); }
    Token new6(int line, int pos) { return new TVoid(line, pos); }
    Token new7(int line, int pos) { return new TMain(line, pos); }
    Token new8(int line, int pos) { return new TString(line, pos); }
    Token new9(int line, int pos) { return new TInt(line, pos); }
    Token new10(int line, int pos) { return new TFloat(line, pos); }
    Token new11(int line, int pos) { return new TFor(line, pos); }
    Token new12(int line, int pos) { return new TWhile(line, pos); }
    Token new13(int line, int pos) { return new TIf(line, pos); }
    Token new14(int line, int pos) { return new TElse(line, pos); }
    Token new15(int line, int pos) { return new TDo(line, pos); }
    Token new16(int line, int pos) { return new TAssign(line, pos); }
    Token new17(String text, int line, int pos) { return new TCompare(text, line, pos); }
    Token new18(int line, int pos) { return new TPlus(line, pos); }
    Token new19(int line, int pos) { return new TMinus(line, pos); }
    Token new20(int line, int pos) { return new TMult(line, pos); }
    Token new21(int line, int pos) { return new TDiv(line, pos); }
    Token new22(int line, int pos) { return new TLPar(line, pos); }
    Token new23(int line, int pos) { return new TRPar(line, pos); }
    Token new24(int line, int pos) { return new TLBrace(line, pos); }
    Token new25(int line, int pos) { return new TRBrace(line, pos); }
    Token new26(int line, int pos) { return new TLBracket(line, pos); }
    Token new27(int line, int pos) { return new TRBracket(line, pos); }
    Token new28(int line, int pos) { return new TComma(line, pos); }
    Token new29(int line, int pos) { return new TSemi(line, pos); }
    Token new30(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    Token new31(String text, int line, int pos) { return new TNumber(text, line, pos); }
    Token new32(String text, int line, int pos) { return new TMisc(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 3}, {14, 31, 1}, {32, 32, 4}, {33, 33, 5}, {34, 39, 1}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 1}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {63, 64, 1}, {65, 90, 19}, {91, 91, 20}, {92, 92, 1}, {93, 93, 21}, {94, 96, 1}, {97, 97, 22}, {98, 98, 23}, {99, 99, 22}, {100, 100, 24}, {101, 102, 22}, {103, 103, 25}, {104, 104, 26}, {105, 105, 22}, {106, 106, 27}, {107, 108, 22}, {109, 109, 28}, {110, 118, 22}, {119, 119, 29}, {120, 120, 22}, {121, 121, 30}, {122, 122, 22}, {123, 123, 31}, {124, 124, 1}, {125, 125, 32}, {126, 65535, 1}, },
            {},
            {},
            {},
            {},
            {{61, 61, 33}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 34}, },
            {{42, 42, 35}, {47, 47, 36}, },
            {{46, 46, 37}, {48, 57, 38}, {69, 69, 39}, {101, 101, 39}, },
            {},
            {{61, 61, 40}, },
            {{61, 61, 41}, },
            {{61, 61, 42}, },
            {{48, 57, 43}, {65, 90, 44}, {95, 95, 45}, {97, 122, 46}, },
            {},
            {},
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 47}, {98, 116, 46}, {117, 117, 48}, {118, 122, 46}, },
            {{48, 95, -21}, {97, 97, 49}, {98, 122, 46}, },
            {{48, 95, -21}, {97, 100, 46}, {101, 101, 50}, {102, 110, 46}, {111, 111, 51}, {112, 122, 46}, },
            {{48, 95, -21}, {97, 97, 52}, {98, 122, 46}, },
            {{48, 100, -27}, {101, 101, 53}, {102, 122, 46}, },
            {{48, 95, -21}, {97, 116, 46}, {117, 117, 54}, {118, 122, 46}, },
            {{48, 95, -21}, {97, 104, 46}, {105, 105, 55}, {106, 122, 46}, },
            {{48, 100, -27}, {101, 101, 56}, {102, 122, 46}, },
            {},
            {},
            {},
            {{48, 57, 34}, {69, 101, -16}, },
            {{0, 41, 57}, {42, 42, 58}, {43, 65535, 57}, },
            {{0, 9, 59}, {10, 10, 60}, {11, 12, 59}, {13, 13, 60}, {14, 65535, 59}, },
            {{48, 57, 61}, {69, 101, -16}, },
            {{46, 101, -16}, },
            {{43, 43, 62}, {45, 45, 62}, {48, 57, 63}, },
            {},
            {},
            {},
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 109, 46}, {110, 110, 64}, {111, 122, 46}, },
            {{48, 95, -21}, {97, 99, 46}, {100, 100, 65}, {101, 122, 46}, },
            {{48, 109, -49}, {110, 110, 66}, {111, 122, 46}, },
            {{48, 116, -30}, {117, 117, 67}, {118, 122, 46}, },
            {{48, 109, -49}, {110, 110, 68}, {111, 122, 46}, },
            {{48, 100, -27}, {101, 101, 69}, {102, 109, 46}, {110, 110, 70}, {111, 122, 46}, },
            {{48, 95, -21}, {97, 110, 46}, {111, 111, 71}, {112, 122, 46}, },
            {{48, 95, -21}, {97, 97, 46}, {98, 98, 72}, {99, 105, 46}, {106, 106, 73}, {107, 122, 46}, },
            {{48, 95, -21}, {97, 103, 46}, {104, 104, 74}, {105, 122, 46}, },
            {{48, 95, -21}, {97, 102, 46}, {103, 103, 75}, {104, 122, 46}, },
            {{0, 65535, -37}, },
            {{0, 41, 76}, {43, 46, 76}, {47, 47, 77}, {48, 65535, 76}, },
            {{0, 65535, -38}, },
            {},
            {{48, 101, -39}, },
            {{48, 57, 63}, },
            {{48, 57, 63}, },
            {{48, 122, -21}, },
            {{48, 110, -55}, {111, 111, 78}, {112, 122, 46}, },
            {{48, 102, -58}, {103, 103, 79}, {104, 122, 46}, },
            {{48, 95, -21}, {97, 113, 46}, {114, 114, 80}, {115, 122, 46}, },
            {{48, 102, -58}, {103, 103, 81}, {104, 122, 46}, },
            {{48, 95, -21}, {97, 114, 46}, {115, 115, 82}, {116, 122, 46}, },
            {{48, 114, -71}, {115, 115, 83}, {116, 122, 46}, },
            {{48, 109, -49}, {110, 110, 84}, {111, 122, 46}, },
            {{48, 95, -21}, {97, 97, 85}, {98, 122, 46}, },
            {{48, 100, -27}, {101, 101, 86}, {102, 122, 46}, },
            {{48, 95, -21}, {97, 97, 87}, {98, 122, 46}, },
            {{48, 95, -21}, {97, 97, 88}, {98, 122, 46}, },
            {{0, 41, 89}, {42, 42, 90}, {43, 65535, 89}, },
            {},
            {{48, 109, -49}, {110, 110, 91}, {111, 122, 46}, },
            {{48, 114, -71}, {115, 115, 92}, {116, 122, 46}, },
            {{48, 100, -27}, {101, 101, 93}, {102, 122, 46}, },
            {{48, 102, -58}, {103, 103, 94}, {104, 122, 46}, },
            {{48, 100, -27}, {101, 101, 95}, {102, 122, 46}, },
            {{48, 116, -30}, {117, 117, 96}, {118, 122, 46}, },
            {{48, 102, -58}, {103, 103, 97}, {104, 122, 46}, },
            {{48, 109, -49}, {110, 110, 98}, {111, 122, 46}, },
            {{48, 110, -55}, {111, 111, 99}, {112, 122, 46}, },
            {{48, 109, -49}, {110, 110, 100}, {111, 122, 46}, },
            {{48, 122, -21}, },
            {{0, 65535, -78}, },
            {{0, 41, 76}, {42, 42, 90}, {43, 65535, -60}, },
            {{48, 102, -58}, {103, 103, 101}, {104, 122, 46}, },
            {{48, 104, -31}, {105, 105, 102}, {106, 122, 46}, },
            {{48, 110, -55}, {111, 111, 103}, {112, 122, 46}, },
            {{48, 110, -55}, {111, 111, 104}, {112, 122, 46}, },
            {{48, 110, -55}, {111, 111, 105}, {112, 122, 46}, },
            {{48, 122, -21}, },
            {{48, 114, -71}, {115, 115, 106}, {116, 116, 107}, {117, 122, 46}, },
            {{48, 114, -71}, {115, 115, 108}, {116, 122, 46}, },
            {{48, 109, -49}, {110, 110, 109}, {111, 122, 46}, },
            {{48, 122, -21}, },
            {{48, 114, -71}, {115, 115, 110}, {116, 122, 46}, },
            {{48, 122, -21}, },
            {{48, 103, -57}, {104, 104, 111}, {105, 122, 46}, },
            {{48, 109, -49}, {110, 110, 112}, {111, 122, 46}, },
            {{48, 109, -49}, {110, 110, 113}, {111, 122, 46}, },
            {{48, 116, -30}, {117, 117, 114}, {118, 122, 46}, },
            {{48, 95, -21}, {97, 97, 115}, {98, 122, 46}, },
            {{48, 100, -27}, {101, 101, 116}, {102, 122, 46}, },
            {{48, 102, -58}, {103, 103, 117}, {104, 122, 46}, },
            {{48, 116, -30}, {117, 117, 118}, {118, 122, 46}, },
            {{48, 95, -21}, {97, 105, 46}, {106, 106, 119}, {107, 122, 46}, },
            {{48, 102, -58}, {103, 103, 120}, {104, 122, 46}, },
            {{48, 102, -58}, {103, 103, 121}, {104, 122, 46}, },
            {{48, 122, -21}, },
            {{48, 100, -27}, {101, 101, 122}, {102, 122, 46}, },
            {{48, 110, -55}, {111, 111, 123}, {112, 122, 46}, },
            {{48, 114, -71}, {115, 115, 124}, {116, 122, 46}, },
            {{48, 122, -21}, },
            {{48, 104, -31}, {105, 105, 125}, {106, 122, 46}, },
            {{48, 99, -50}, {100, 100, 126}, {101, 122, 46}, },
            {{48, 122, -21}, },
            {{48, 116, -30}, {117, 117, 127}, {118, 122, 46}, },
            {{48, 109, -49}, {110, 110, 128}, {111, 122, 46}, },
            {{48, 116, -30}, {117, 117, 129}, {118, 122, 46}, },
            {{48, 122, -21}, },
            {{48, 100, -27}, {101, 101, 130}, {102, 122, 46}, },
            {{48, 104, -31}, {105, 105, 131}, {106, 122, 46}, },
            {{48, 102, -58}, {103, 103, 132}, {104, 122, 46}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 32, 2, 2, 2, 32, 22, 23, 20, 18, 28, 19, 32, 21, 31, 29, 17, 16, 17, 30, 26, 27, 30, 30, 30, 30, 30, 30, 30, 30, 30, 24, 25, 17, 31, -1, -1, 31, 31, -1, 17, 17, 17, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, -1, -1, -1, 0, 31, -1, 31, 3, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, -1, 1, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 13, -1, -1, 30, 30, 30, 30, 30, 7, 30, 30, 30, 11, 30, 12, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 9, 30, 30, 30, 10, 30, 30, 15, 30, 30, 30, 14, 30, 30, 30, 8, 4, 5, 6, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
