/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.analysis;

import decaf.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseTComment1(TComment1 node);
    void caseTComment2(TComment2 node);
    void caseTSpace(TSpace node);
    void caseTClas(TClas node);
    void caseTPublic(TPublic node);
    void caseTStatic(TStatic node);
    void caseTVoid(TVoid node);
    void caseTMain(TMain node);
    void caseTString(TString node);
    void caseTInt(TInt node);
    void caseTFloat(TFloat node);
    void caseTFor(TFor node);
    void caseTWhile(TWhile node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTAssign(TAssign node);
    void caseTCompare(TCompare node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTComma(TComma node);
    void caseTSemi(TSemi node);
    void caseTIdentifier(TIdentifier node);
    void caseTNumber(TNumber node);
    void caseTMisc(TMisc node);
    void caseEOF(EOF node);
}
